<?php

namespace App\Support;

class PurchaseCandidateCategoryMap
{
    private const MAP = [
        'tops_tshirt_cutsew' => ['category' => 'tops', 'shape' => 'tshirt'],
        'tops_shirt_blouse' => ['category' => 'tops', 'shape' => 'shirt'],
        'tops_knit_sweater' => ['category' => 'tops', 'shape' => 'knit'],
        'tops_polo_shirt' => ['category' => 'tops', 'shape' => 'shirt'],
        'tops_sweat_trainer' => ['category' => 'tops', 'shape' => 'jacket'],
        'tops_hoodie' => ['category' => 'tops', 'shape' => 'jacket'],
        'tops_cardigan' => ['category' => 'tops', 'shape' => 'cardigan'],
        'tops_vest_gilet' => ['category' => 'tops', 'shape' => 'camisole'],
        'tops_camisole' => ['category' => 'tops', 'shape' => 'camisole'],
        'tops_tanktop' => ['category' => 'tops', 'shape' => 'tanktop'],
        'tops_other' => ['category' => 'tops', 'shape' => 'jacket'],
        'outerwear_jacket' => ['category' => 'outer', 'shape' => 'tailored'],
        'outerwear_coat' => ['category' => 'outer', 'shape' => 'trench'],
        'outerwear_blouson' => ['category' => 'outer', 'shape' => 'outer-cardigan'],
        'outerwear_down_padded' => ['category' => 'outer', 'shape' => 'down'],
        'outerwear_mountain_parka' => ['category' => 'outer', 'shape' => 'outer-cardigan'],
        'outerwear_other' => ['category' => 'outer', 'shape' => 'outer-cardigan'],
        'pants_pants' => ['category' => 'bottoms', 'shape' => 'straight'],
        'pants_denim' => ['category' => 'bottoms', 'shape' => 'straight'],
        'pants_slacks' => ['category' => 'bottoms', 'shape' => 'tapered'],
        'pants_short' => ['category' => 'bottoms', 'shape' => 'wide'],
        'pants_other' => ['category' => 'bottoms', 'shape' => 'straight'],
        'skirts_skirt' => ['category' => 'bottoms', 'shape' => 'a-line-skirt'],
        'skirts_other' => ['category' => 'bottoms', 'shape' => 'a-line-skirt'],
        'onepiece_dress_onepiece' => ['category' => 'onepiece_allinone', 'shape' => 'onepiece'],
        'onepiece_dress_dress' => ['category' => 'onepiece_allinone', 'shape' => 'onepiece'],
        'onepiece_dress_other' => ['category' => 'onepiece_allinone', 'shape' => 'onepiece'],
        'allinone_allinone' => ['category' => 'onepiece_allinone', 'shape' => 'allinone'],
        'allinone_salopette' => ['category' => 'onepiece_allinone', 'shape' => 'allinone'],
        'allinone_other' => ['category' => 'onepiece_allinone', 'shape' => 'allinone'],
        'roomwear_inner_roomwear' => ['category' => 'inner', 'shape' => 'roomwear'],
        'roomwear_inner_underwear' => ['category' => 'inner', 'shape' => 'underwear'],
        'roomwear_inner_pajamas' => ['category' => 'inner', 'shape' => 'pajamas'],
        'shoes_sneakers' => ['category' => 'shoes', 'shape' => 'sneakers'],
        'shoes_loafers_leather' => ['category' => 'shoes', 'shape' => 'pumps'],
        'shoes_pumps' => ['category' => 'shoes', 'shape' => 'pumps'],
        'shoes_boots' => ['category' => 'shoes', 'shape' => 'short-boots'],
        'shoes_sandals' => ['category' => 'shoes', 'shape' => 'sandals'],
        'shoes_other' => ['category' => 'shoes', 'shape' => 'sneakers'],
        'legwear_other' => ['category' => 'legwear', 'shape' => 'socks'],
        'bags_bag' => ['category' => 'bags', 'shape' => 'bag'],
        'bags_other' => ['category' => 'bags', 'shape' => 'bag'],
        'fashion_accessories_hat' => ['category' => 'fashion_accessories', 'shape' => 'hat'],
        'fashion_accessories_belt' => ['category' => 'fashion_accessories', 'shape' => 'belt'],
        'fashion_accessories_scarf_stole' => ['category' => 'fashion_accessories', 'shape' => 'scarf-stole'],
        'fashion_accessories_gloves' => ['category' => 'fashion_accessories', 'shape' => 'gloves'],
        'fashion_accessories_jewelry' => ['category' => 'fashion_accessories', 'shape' => 'jewelry'],
        'fashion_accessories_wallet_case' => ['category' => 'fashion_accessories', 'shape' => 'wallet-case'],
        'fashion_accessories_hair' => ['category' => 'fashion_accessories', 'shape' => 'hair-accessory'],
        'fashion_accessories_eyewear' => ['category' => 'fashion_accessories', 'shape' => 'eyewear'],
        'fashion_accessories_watch' => ['category' => 'fashion_accessories', 'shape' => 'watch'],
        'fashion_accessories_other' => ['category' => 'fashion_accessories', 'shape' => 'other'],
        'swimwear_swimwear' => ['category' => 'swimwear', 'shape' => 'swimwear'],
        'swimwear_rashguard' => ['category' => 'swimwear', 'shape' => 'rashguard'],
        'swimwear_other' => ['category' => 'swimwear', 'shape' => 'other'],
        'kimono_kimono' => ['category' => 'kimono', 'shape' => 'kimono'],
        'kimono_other' => ['category' => 'kimono', 'shape' => 'other'],
        // 旧 category_id を持つ購入検討データ用の互換マップ
        'tops_tshirt' => ['category' => 'tops', 'shape' => 'tshirt'],
        'tops_shirt' => ['category' => 'tops', 'shape' => 'shirt'],
        'tops_knit' => ['category' => 'tops', 'shape' => 'knit'],
        'tops_vest' => ['category' => 'tops', 'shape' => 'camisole'],
        'outer_jacket' => ['category' => 'outer', 'shape' => 'tailored'],
        'outer_coat' => ['category' => 'outer', 'shape' => 'trench'],
        'outer_blouson' => ['category' => 'outer', 'shape' => 'outer-cardigan'],
        'outer_down' => ['category' => 'outer', 'shape' => 'down'],
        'outer_other' => ['category' => 'outer', 'shape' => 'outer-cardigan'],
        'bottoms_pants' => ['category' => 'bottoms', 'shape' => 'straight'],
        'bottoms_skirt' => ['category' => 'bottoms', 'shape' => 'a-line-skirt'],
        'bottoms_shorts' => ['category' => 'bottoms', 'shape' => 'wide'],
        'bottoms_other' => ['category' => 'bottoms', 'shape' => 'straight'],
        'onepiece' => ['category' => 'onepiece_allinone', 'shape' => 'onepiece'],
        'allinone' => ['category' => 'onepiece_allinone', 'shape' => 'allinone'],
        'inner_roomwear' => ['category' => 'inner', 'shape' => 'roomwear'],
        'inner_underwear' => ['category' => 'inner', 'shape' => 'underwear'],
        'inner_pajamas' => ['category' => 'inner', 'shape' => 'pajamas'],
        'shoes_loafers' => ['category' => 'shoes', 'shape' => 'pumps'],
        'bags_hand' => ['category' => 'bags', 'shape' => 'bag'],
        'bags_shoulder' => ['category' => 'bags', 'shape' => 'shoulder'],
        'bags_tote' => ['category' => 'bags', 'shape' => 'tote'],
        'bags_backpack' => ['category' => 'bags', 'shape' => 'backpack'],
        'bags_body' => ['category' => 'bags', 'shape' => 'shoulder'],
        'bags_clutch' => ['category' => 'bags', 'shape' => 'clutch'],
        'accessories_hat' => ['category' => 'fashion_accessories', 'shape' => 'hat'],
        'accessories_belt' => ['category' => 'fashion_accessories', 'shape' => 'belt'],
        'accessories_scarf' => ['category' => 'fashion_accessories', 'shape' => 'scarf-stole'],
        'accessories_gloves' => ['category' => 'fashion_accessories', 'shape' => 'gloves'],
        'accessories_jewelry' => ['category' => 'fashion_accessories', 'shape' => 'jewelry'],
        'accessories_other' => ['category' => 'fashion_accessories', 'shape' => 'other'],
    ];

    public static function resolveItemDraftCategory(string $categoryId): ?array
    {
        return self::MAP[$categoryId] ?? null;
    }
}
