export const ITEM_THUMBNAIL_VIEWPORT_SIZE = 120;
export const ITEM_THUMBNAIL_FRAME_X = 22;
export const ITEM_THUMBNAIL_FRAME_Y = 20;
export const ITEM_THUMBNAIL_FRAME_WIDTH = 76;
export const ITEM_THUMBNAIL_FRAME_HEIGHT = 72;
export const ITEM_THUMBNAIL_FRAME_RX = 18;
